extends RefCounted
## Turns one `E###.BIN` into the `E###/` directory `addons/exmateria_effects` loads.
##
## This is the SECOND serializer over a shared parse. TacticsG already exports every effect as
## `EXPORT_PATH/vfx/E###.vfx_data.tres` + `.webp` through `VisualEffectData`; that path is
## untouched and still feeds `ProjectileEffectInstance` and the data model. What was missing
## was the addon's format, which used to be generated by `parse_effect.py` in the upstream
## monorepo and COPIED in. The parse half now lives beside this file, vendored from upstream
## (see `tools/effects/vendor_effect_bin.py`), so the only TacticsG-owned code here is the
## mapping from parsed blocks to leaf files.
##
## 🔴 `build()` IS PURE AND `write()` IS NOT, and the split is load-bearing rather than tidy.
## Binary-format work fails as WRONG OUTPUT, not as a crash, so the acceptance test has to be
## able to compare a parse against the known-good `content/effects/E###/` WITHOUT writing
## anything — `tools/effects/effect_extract_regression.tscn` scores `build()` directly. If the
## serializer could only be observed through the filesystem, every test would be scoring the
## disk instead of the parse.
##
## 🔴 A MISSING MANDATORY SECTION IS AN ERROR, NOT A DEFAULT. `parse_effect.py` writes
## `parsed[key]` unconditionally and the vendored readers return `null` for an absent section,
## so a leaf could quietly become `null` or `{}` — and an effect whose `emitters.json` is `[]`
## initializes, simulates nothing and draws nothing, which is the exact silent failure this
## integration keeps producing. `build()` reports the absence by name instead.
##
## ⚠️ `feds.json` IS DELIBERATELY NOT EMITTED. Decoding the FEDS blob needs the opcode table,
## which lives in `addons/exmateria_sound/runtime/sound_opcodes.gd` — the copy that actually
## PLAYS `feds.bin` — and upstream declined to put a third copy in `exmateria_effects` for the
## same reason. Nothing in this repo reads `feds.json`: `EffectData.load_from_directory` loads
## `feds.bin` only. An unread file that can silently drift from the table that plays it is
## worse than no file.

const BinHeader := preload("res://src/file_formats/vfx/effect_bin/EffectBinHeader.gd")
const BinReader := preload("res://src/file_formats/vfx/effect_bin/EffectBinReader.gd")
const ReadTexture := preload("res://src/file_formats/vfx/effect_bin/readers/EffectReadTexture.gd")
const ReadFrames := preload("res://src/file_formats/vfx/effect_bin/readers/EffectReadFrames.gd")
const ReadEmitters := preload("res://src/file_formats/vfx/effect_bin/readers/EffectReadEmitters.gd")
const ReadCurves := preload("res://src/file_formats/vfx/effect_bin/readers/EffectReadCurves.gd")
const ReadScript := preload("res://src/file_formats/vfx/effect_bin/readers/EffectReadScript.gd")
const TextureTga := preload("res://src/file_formats/vfx/effect_bin/TextureTga.gd")
const EffectCallbacksScript := preload("res://src/file_formats/vfx/effect_callbacks.gd")

## Where the addon reads its ROM-derived content from, and the `effects/` tree under it.
##
## 🔴 THIS IS NOT `EXPORT_PATH`, AND IT CANNOT BE. Everything else TacticsG exports lands in
## the external export directory and is read back with `FileAccess`, which is happy with any
## absolute path. Effects content is not: `EffectData.load_from_directory` loads the sheet
## through `ResourceLoader.exists()` + `load()`, which only answer for a path under `res://`
## that Godot has IMPORTED. An unimported `.tga` is SKIPPED, with no error and no warning, and
## the effect then initializes, simulates its particles and draws nothing whatsoever. So the
## extract is written into the project, where the importer can reach it, and `export_vfx()`
## reports the import state rather than assuming it.
const CONTENT_ROOT: String = "res://content/"
const EFFECTS_DIR: String = CONTENT_ROOT + "effects/"

## Registered section -> the leaf carrying it. Every one of these must parse; see the header.
const SECTION_LEAVES: Dictionary = {
	"emitters": "emitters.json",
	"frames": "frames.json",
	# ⚠️ PLURAL leaf, singular section — the vendored reader names it `animation`.
	"animation": "animations.json",
	# ⚠️ the section is `particle_timeline`; the leaf is `timeline.json`.
	"particle_timeline": "timeline.json",
	"screen": "screen.json",
	"palette": "palette.json",
	"camera": "camera.json",
	"effect_flags": "effect_flags.json",
}

## Written only when the section is present. `time_scale` is absent for 269 of 401 effects, and
## an absent section is not a section of zeroes.
const OPTIONAL_SECTION_LEAVES: Dictionary = {
	"time_scale": "time_scale.json",
}

## The two sound leaves ride with `feds.bin`'s presence, matching `save_effect`: a soundless
## effect gets neither, rather than a resolver config for sounds it cannot play.
const SOUND_SECTION_LEAVES: Dictionary = {
	"sound_containers": "sound_containers.json",
	"sound": "sound.json",
}


## Every leaf of one effect, as `{"ok": bool, "leaves": {name -> value}, "errors": [String]}`.
##
## `leaves` values are Dictionaries/Arrays for the `.json` leaves and `PackedByteArray` for
## `feds.bin` / `texture.tga`; `write()` dispatches on the type. `battle_bin` may be empty, in
## which case the header offset falls back to the prologue scan — which MISSES E259/E338/E464.
## Pass it.
static func build(buf: PackedByteArray, battle_bin: PackedByteArray, vfx_id: int,
		effect_name: String) -> Dictionary:
	var errors: Array[String] = []
	var leaves: Dictionary = {}
	if buf.size() < BinHeader.HEADER_SIZE:
		errors.append("%s: %d bytes, too short to hold a header" % [effect_name, buf.size()])
		return {"ok": false, "leaves": leaves, "errors": errors}

	var base: int = BinHeader.header_offset(buf, battle_bin, vfx_id)
	var header: Dictionary = BinHeader.parse_header(buf, base)
	var blocks: Dictionary = BinReader.parse_all(buf, header)

	leaves["header.json"] = BinHeader.header_document("%s.BIN" % effect_name, buf, base)

	for section: String in SECTION_LEAVES:
		if not blocks.has(section):
			errors.append("%s: mandatory section '%s' did not parse" % [effect_name, section])
			continue
		leaves[SECTION_LEAVES[section]] = blocks[section]

	for section: String in OPTIONAL_SECTION_LEAVES:
		if blocks.has(section):
			leaves[OPTIONAL_SECTION_LEAVES[section]] = blocks[section]

	# FEDS: the raw blob is the addon's playback source, and the two sound leaves follow it.
	if blocks.has("sound_def"):
		leaves["feds.bin"] = blocks["sound_def"]
		for section: String in SOUND_SECTION_LEAVES:
			if blocks.has(section):
				leaves[SOUND_SECTION_LEAVES[section]] = blocks[section]

	# --- the derived VIEWS: leaves the section registry does not return ---
	_add_view(leaves, errors, effect_name, "particle_header.json",
		ReadEmitters.particle_header(buf, header))
	_add_view(leaves, errors, effect_name, "curves.json", ReadCurves.parse(buf, header))
	_add_view(leaves, errors, effect_name, "script.json", ReadScript.parse(buf, header))
	_add_view(leaves, errors, effect_name, "texture_meta.json", ReadTexture.meta(buf, header))
	_add_view(leaves, errors, effect_name, "texture_palette.json",
		ReadTexture.swatches(buf, header))

	# Conditional in `save_effect` — written only when non-empty.
	var groups = ReadFrames.group_sizes(buf, header)
	if groups is Array and not (groups as Array).is_empty():
		leaves["frameset_groups.json"] = groups

	var tga: PackedByteArray = build_texture_tga(buf, header)
	if tga.is_empty():
		errors.append("%s: texture.tga could not be decoded" % effect_name)
	else:
		leaves["texture.tga"] = tga

	# The bespoke MIPS callback tables — eight effects, nothing for the other 393. Keyed by a
	# NESTED path (`callbacks/CB##/callback_data.json`), which `write()` handles; the addon
	# looks for exactly that shape.
	var emitters: Array = leaves.get("emitters.json", []) as Array
	var callbacks: Dictionary = EffectCallbacksScript.build(effect_name, buf, emitters)
	for leaf: String in callbacks:
		leaves[leaf] = callbacks[leaf]

	return {"ok": errors.is_empty(), "leaves": leaves, "errors": errors}


## The RGBA sheet as TGA bytes, or empty when the section cannot be sized.
##
## 🔴 THE CLUT LINE IS DEPTH-DEPENDENT AND THAT IS NOT A CHOICE MADE HERE. 8bpp reads all 256
## entries of line 1; 4bpp reads the first 16 of line TWO. `extract_effect_texture.lua`
## produced every committed `texture.tga` that way, so decoding through line 1 instead would
## disagree with the shipped content on exactly the 60 4bpp effects and nowhere else — a
## difference that looks like a palette bug at runtime rather than a decode bug here.
## `EXPAND_TRUNCATE` is the same story: it is what the committed sheets went through.
static func build_texture_tga(buf: PackedByteArray, header: Dictionary) -> PackedByteArray:
	var depth = ReadTexture.sheet_depth(buf, header)
	if depth == null:
		return PackedByteArray()
	var is_8bpp: bool = bool(depth)
	var size: Vector2i = ReadTexture.dimensions(buf, header, is_8bpp)
	if size.x <= 0 or size.y <= 0:
		return PackedByteArray()
	var pixels: PackedByteArray = ReadTexture.decode_rgba(buf, header, is_8bpp, not is_8bpp, 0,
		ReadTexture.EXPAND_TRUNCATE)
	if pixels.size() != size.x * size.y * 4:
		return PackedByteArray()
	return TextureTga.encode(size.x, size.y, pixels)


## Write one effect's leaves into `dir_path`, creating it. Returns `{"ok", "errors"}`.
##
## Leaves are written but nothing is REMOVED: regenerating over an existing directory leaves
## any file this build did not produce exactly where it was. That matters for two of them —
## `feds.json`, which this extractor deliberately does not emit, and `texture.tga.import`,
## which belongs to Godot's importer and must survive (see `EffectExtractImport`).
static func write(leaves: Dictionary, dir_path: String) -> Dictionary:
	var errors: Array[String] = []
	var err: Error = DirAccess.make_dir_recursive_absolute(dir_path)
	if err != OK and not DirAccess.dir_exists_absolute(dir_path):
		return {"ok": false, "errors": ["%s: %s" % [dir_path, error_string(err)]]}

	for leaf: String in leaves:
		var path: String = dir_path.path_join(leaf)
		# `callbacks/CB##/callback_data.json` is a nested leaf, so the parent may not exist.
		if leaf.contains("/"):
			DirAccess.make_dir_recursive_absolute(path.get_base_dir())
		var value = leaves[leaf]
		var bytes: PackedByteArray
		if value is PackedByteArray:
			bytes = value
		else:
			bytes = to_json(value).to_utf8_buffer()
		var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
		if file == null:
			errors.append("%s: %s" % [path, error_string(FileAccess.get_open_error())])
			continue
		file.store_buffer(bytes)
		file.close()
	return {"ok": errors.is_empty(), "errors": errors}


## One leaf's JSON text.
##
## 🔴 `full_precision` IS NOT OPTIONAL. `JSON.stringify` defaults it to FALSE, which rounds
## floats to ~6 significant digits — and this format is mostly converted doubles (positions,
## velocities, accelerations, gravity). The rounding is silent, survives reparsing, and shows
## up as effects that play slightly wrong rather than as an error. `sort_keys` is off so the
## leaves keep the readers' natural field order, which keeps a `diff` against the previously
## shipped content readable by a human.
static func to_json(value) -> String:
	return JSON.stringify(value, "  ", false, true)


static func _add_view(leaves: Dictionary, errors: Array[String], effect_name: String,
		leaf: String, value) -> void:
	if value == null:
		errors.append("%s: view '%s' did not parse" % [effect_name, leaf])
		return
	leaves[leaf] = value
