shader_type spatial;
render_mode unshaded, cull_disabled, depth_draw_opaque;

uniform sampler2D sprite_texture : source_color, filter_nearest;
uniform vec4[16] palette_colors : source_color; // palette of 16 colors each
uniform vec3 unit_tint = vec3(0.0, 0.0, 0.0);
uniform bool billboard_enabled = false;

#include "res://src/shaders/psx_depth_common.gdshaderinc"

void vertex() {
	if (billboard_enabled) {
		mat4 modified_model_view = VIEW_MATRIX * mat4(
			INV_VIEW_MATRIX[0], // Camera X (Right vector)
			INV_VIEW_MATRIX[1], // Camera Y (Up vector)
			INV_VIEW_MATRIX[2], // Camera Z (Forward vector)
			MODEL_MATRIX[3]     // Keeps the object's original 3D position
		);
		MODELVIEW_MATRIX = modified_model_view;
		// Fix normals so lighting doesn't break
		MODELVIEW_NORMAL_MATRIX = mat3(MODELVIEW_MATRIX);
	}
	
	computed_depth = psx_depth(
		MODEL_MATRIX[3].xyz, PROJECTION_MATRIX, VIEW_MATRIX,
		INV_VIEW_MATRIX[3].xyz, depth_mode, depth_bias_custom);
}

void fragment() {
	vec4 tex = texture(sprite_texture, UV);
	int palette_index = int(round(tex.x * 255.0));
	tex = palette_colors[palette_index];
	vec4 col = tex * COLOR;
	if (col.a < 0.5) {
		discard;
	}
	ALBEDO = clamp(col.rgb + unit_tint, vec3(0.0), vec3(1.0));
	DEPTH = computed_depth;
}
